pipeline {
    agent {
        docker {
            image 'node:14-alpine'
        }
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello Callahan'
            }
        }
        
        stage('Test the NodeJS') {
            steps {
                sh 'node --version'
            }
        }
    }
}
